#!/bin/bash
vol(){
    vol=$(pulsemixer --get-volume | awk '{print $1}')
	printf "%s" "vol ^c#c6c8d1^$vol%^d^"
}

bat() {
	power=$(cat /sys/class/power_supply/BAT0/capacity)
	printf "%s" "bat ^c#c6c8d1^$power%^d^"
}

dte() {
    dte=$(date +"%A, %B %d")
    printf "%s" "date ^c#c6c8d1^$dte^d^"
}

tie() {
    tme=$(date +"%I:%M %p")
    printf "%s" "time ^c#c6c8d1^$tme^d^"
}
while true; do
    xsetroot -name "$(vol) $(bat) $(tie) $(dte)"
    sleep 3
done
